name: windows

on: workflow_dispatch

env:
  SOURCE_URL: https://www.sqlite.org/2022/sqlite-amalgamation-3390300.zip

jobs:
  build_windows:
    name: build_windows
    strategy:
      matrix:
        arch: ["amd64"]

    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download source
        run: |
          aria2c.exe -o src.zip ${{ env.SOURCE_URL }} --check-certificate=false
          7z e src.zip -y -osrc
          mkdir build32
          mkdir build64

      - name: build x86
        run: |
          cmake .. -A Win32
          cmake --build . --target ALL_BUILD
          ls
        working-directory: ./build32

      - name: build x64
        run: |
          cmake .. -A x64
          cmake --build . --target ALL_BUILD
          ls
        working-directory: ./build64
