name: windows

on: workflow_dispatch

env:
  SOURCE_URL: https://www.sqlite.org/2022/sqlite-amalgamation-3390300.zip

jobs:
  build_windows:


    name: build_windows
    strategy:
      matrix:
        arch: ["amd64_x86","amd64"]
        link: ["dll","lib"]

    runs-on: windows-latest
    steps:
      - name: download source
        run: aria2c.exe -o source.zip ${{ env.SOURCE_URL }} --check-certificate=false

      - name: unzip file
        run: 7z e source.zip -y -oSource

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: build
        working-directory: ./Source
        run: cl.exe sqlite3.c -link -dll -out:sqlite3.dll

      - name: check build
        working-directory: ./Source
        run: ls
