name: windows

on: workflow_dispatch

env:
  SOURCE_URL: https://www.sqlite.org/2022/sqlite-amalgamation-3390300.zip

jobs:
  build_windows:
    name: build_windows
    strategy:
      matrix:
        arch: ["amd64_x86","amd64"]

    runs-on: windows-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download source
        run: aria2c.exe -o src.zip ${{ env.SOURCE_URL }} --check-certificate=false

      - name: unzip file
        run: |
          7z e src.zip -y -osrc
          mkdir build

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: build
        run: |
          cmake ..
          cmake --build . --target ALL_BUILD
        working-directory: ./build

      - name: check build
        run: ls
        working-directory: ./build
