name: windows

on: workflow_dispatch

env:
  SOURCE_URL: https://www.sqlite.org/2022/sqlite-amalgamation-3390300.zip

jobs:
  build_windows:


    name: build_windows
    strategy:
      matrix:
        arch: ["amd64_x86","amd64"]
        config: [
          {
            link: ["/MD"],
            file: "sqlite3.dll"
          },
          {
            link: ["/MDd"],
            file: "sqlite3d.dll"
          },
          {
            link: ["/MT"],
            file: "sqlite3.lib"
          },
          {
            link: ["/MTd"],
            file: "sqlite3d.lib"
          }
          ]

    runs-on: windows-latest
    steps:
      - name: download source
        run: aria2c.exe -o source.zip ${{ env.SOURCE_URL }} --check-certificate=false

      - name: unzip file
        run: 7z e source.zip -y -oSource

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: build
        working-directory: ./Source
        run: cl.exe /O1 /O1 ${{ matrix.config.link }} sqlite3.c -out:${{ matrix.config.file }}

      - name: check build
        working-directory: ./Source
        run: ls
